name: CV building

on: [push]

jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install
      - run: npm run build-css
      - run: npm run build-html
      - name: Push CV to the djbelyak.ru repo
        uses: datalbry/copy_folder_to_another_repo_action@1.0.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'dist'
          destination_repo: 'djbelyak/djbelyak.ru'
          destination_folder: 'static/CV'
          user_email: 'djbelyak@gmail.com'
          user_name: 'djbelyak'