name: CV building

on: [push]

jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run build-css
      - run: npm run build-htmls
      - name: Push CV to the djbelyak.ru repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'dist'
          destination-repository-name: 'djbelyak.ru'
          target-branch: master
          target-directory: 'static/CV'